### ISSUE TITLE
Exceptions in Symfony 3.1.2 using bundle v2.2.0

### ISSUE THREAD

**Issue by janwebdev** [BranchBit/AsyncDispatcherBundle#10]
InvalidArgumentException in YamlFileLoader.php line 371:
The file "C:\wamp\www\litelab.dev\vendor\bbit\async-dispatcher-bundle\BBIT\AsyncDispatcherBundle\DependencyInjection/../Resources/config\services.yml" does not contain valid YAML.

ParseException in Inline.php line 316:
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 12 (near "- @event_dispatcher").

**Comment by whitewhidow** [comment]
fixed in https://github.com/BranchBit/AsyncDispatcherBundle/releases/tag/2.3
